jumps: 86400
start_date: "2018-09-17"
end_date: "2026-03-17"
root: "./data"
date_format: "%Y-%m-%d"
data_path: "./data/one_day_pred.csv"
train_interval: ["2018-09-17","2024-10-01"]
val_interval: ["2024-10-01", "2025-10-01"]
test_interval: ["2025-10-01", "2026-03-17"]
additional_features: []